ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.RoutingKt.configureRouting
      - com.example.MainKt.module

db:
  host: "$DB_HOST:localhost"
  port: "$DB_PORT:5432"
  username: "$DB_USERNAME:app"
  password: "$DB_PASSWORD:password"
  name: "$DB_NAME:tgbot"

tg:
  token: "$TG_TOKEN"
