apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
    spec:
      containers:
        - name: tg-bot
          image: registry.rutbot.com/tg-bot
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ .Values.application.name }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - {{ .Values.application.node }}