application:
  name: tg-bot
  node: rut-master

telegram:
  botToken: ""
  botUsername: "marktestbot"
  autoRegister: "true"

scenario:
  activeProfile: "exchange-aggregator"

replicaCount: 1

database:
  host: ""
  port: ""
  name: ""
  user: ""
  password: ""

