
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: tg-bot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
#    strategy:
#      max-parallel: 4
#      matrix:
#        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image with latest tag
        run: docker build . --file Dockerfile --tag registry.rutbot.com/tg-bot:latest

      - name: Publish image to docker hub
        run: docker push registry.rutbot.com/tg-bot:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Create kubeconfig file
        run: echo "${{ secrets.KUBECONFIG }}" > ${{ github.workspace }}/kubeconfig

      - name: Update helm
        run: |
          helm package ./helm/${{ github.event.repository.name }}
          helm push ${{ github.event.repository.name }}-0.1.0.tgz oci://registry.rutbot.com/rut-charts

      - name: Deploy to Kubernetes using Helm
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          helm upgrade --install tg-bot oci://registry.rutbot.com/rut-charts/${{ github.event.repository.name }} \
            --set telegram.botToken="${{ secrets.TELEGRAM_TOKEN }}" \
            --set application.node=rut-master \
            --set database.host="${{ secrets.DB_HOST }}" \
            --set database.port="${{ secrets.DB_PORT }}" \
            --set database.name="${{ secrets.DB_NAME }}" \
            --set database.user="${{ secrets.DB_USER }}" \
            --set database.password="${{ secrets.DB_PASSWORD }}" \
